# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=kursy
    ports:
      - "3306:3306"

